### ISSUE TITLE
Get All Posts Endpoint

### ISSUE THREAD

**Issue by carlosfurnari** [7552-2C-2018/App-Server#6]
Endpoint for getting all the posts available

Method: GET

Response Body:
{"posts" :[
			{
				"id": int,
				"title": string,
				"image": string,
				"price": int
			},
			...
		]
}

**Comment by carlosfurnari** [comment]
generar este reducido /reduced y reemplazar el actual get_all que trae mas campos de los necesarios

**Comment by IgnacioManes** [comment]
al final quedo con un /products para todos los productos, y /products/<id> para un unico producto
